#
# Makefile for the Freecomm drivers.
#

# Each configuration option enables a list of files.


obj-$(CONFIG_DEVICE_VERSION)    += devices_version.o
obj-$(CONFIG_BATT_RTC_ALARM)    += batt_rtc_alarm.o
obj-$(CONFIG_TP_FIRMWARE_VERSION) += touchpanel_Firmware.o # add tp firmware version Manager

